name: flow app
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test command
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run build command
        run: npm run build
